"""auto-generate

Revision ID: 6978db7cdb63
Revises: 
Create Date: 2022-10-16 15:46:12.806403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6978db7cdb63'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('user_name', sa.String(), nullable=False),
                    sa.Column('display_name', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('last_login', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('is_active', sa.Boolean(),
                              server_default='TRUE', nullable=True),
                    sa.Column('is_deleted', sa.Boolean(),
                              server_default='FALSE', nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('user_id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('boards',
                    sa.Column('board_id', sa.BigInteger(), nullable=False),
                    sa.Column('board_name', sa.String(), nullable=False),
                    sa.Column('project_id', sa.BigInteger(), nullable=False),
                    sa.Column('board_creator_id',
                              sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['board_creator_id'], [
                        'users.user_id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['users.user_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('board_id')
                    )
    op.create_table('projects',
                    sa.Column('project_id', sa.BigInteger(), nullable=False),
                    sa.Column('project_name', sa.String(), nullable=False),
                    sa.Column('project_creator_id',
                              sa.BigInteger(), nullable=True),
                    sa.Column('project_start_date', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('project_end_date', sa.TIMESTAMP(
                        timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['project_creator_id'], [
                        'users.user_id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('project_id')
                    )
    op.create_table('UsersProjectsMap',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('project_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['projects.project_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'project_id')
                    )
    op.create_table('columns',
                    sa.Column('column_id', sa.BigInteger(), nullable=False),
                    sa.Column('column_name', sa.String(), nullable=False),
                    sa.Column('board_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['board_id'], ['boards.board_id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('column_id')
                    )
    op.create_table('ColumnsFlow',
                    sa.Column('from_column_id',
                              sa.BigInteger(), nullable=False),
                    sa.Column('to_column_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['from_column_id'], [
                                            'columns.column_id'], ),
                    sa.ForeignKeyConstraint(
                        ['to_column_id'], ['columns.column_id'], ),
                    sa.PrimaryKeyConstraint('from_column_id', 'to_column_id')
                    )
    op.create_table('tickets',
                    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
                    sa.Column('ticket_name', sa.String(), nullable=False),
                    sa.Column('ticket_creator_id',
                              sa.BigInteger(), nullable=True),
                    sa.Column('ticket_creation_date', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('ticket_column_id',
                              sa.BigInteger(), nullable=True),
                    sa.Column('assignee_id', sa.BigInteger(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['assignee_id'], ['users.user_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['ticket_column_id'], [
                        'columns.column_id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(['ticket_creator_id'], [
                        'users.user_id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('ticket_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('ColumnsFlow')
    op.drop_table('columns')
    op.drop_table('UsersProjectsMap')
    op.drop_table('projects')
    op.drop_table('boards')
    op.drop_table('users')
    # ### end Alembic commands ###
